### ISSUE TITLE
Have you published part 2 of this article yet? 

### ISSUE THREAD

**Issue by hieu-ht** [simonrenoult/nodejs-application-architecture#13]

**Comment by ajbkr** [comment]
I too was looking forward to parts 2 and 3. 😥

**Comment by simonrenoult** [comment]
Hi,

Life got in the way and I no longer have the time or will to release part 2 or 3.
In the meantime, others have done a much better job than anything I would ever do.

To name a few:
- Khalil Stemmer :
  -  His blog is full of gems: https://khalilstemmler.com/articles/categories/enterprise-node-type-script/
  - His book "SOLID" seems solid (pun intended): https://solidbook.io/
- Martin Fowler : https://martinfowler.com/books/refactoring.html
- Nicolas Carlo : https://understandlegacycode.com/
