### ISSUE TITLE
npm start fails because of ./bin/start, const api 

### ISSUE THREAD

**Issue by Goumies** [simonrenoult/nodejs-application-architecture#9]
Hello, 
As a beginner dev and newly trained in software craftmanship and principles like SOLID in Java, I'm learning how to implement clean architecture in nodeJS. Thanks to features like yours in [medium](https://medium.com/the-node-js-collection/clean-node-1df635d176f7).

I'm having a hard time running the project.

I get 'Cannot find module '..'' because of `const api = require("..");`, in start.js.

Is there something missing ? What module this const is referring to, please ?

**Comment by simonrenoult** [comment]
Hi @Goumies,

The `require("..")` statement is an alias for `require("../index.js")`. It's a common shortcut in Node.js, though Ryan Dahl, creator of Node.js [regrets this decision](https://www.youtube.com/watch?v=M3BM9TB-8yA&t=880s) now.

You can learn more about the Node.js modules system [here](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8).

Hope this helps!
